### ISSUE TITLE
Language server not working

### ISSUE THREAD

**Issue by affanshahid** [nusnewob/caddyfile-zed#1]
Whenever I open a caddyfile I see "language server failed" in the status bar with the following error:
```
Language server error: caddyfile

oneshot canceled
-- stderr--

```

**Comment by matheus-de-araujo** [comment]
This error likely occurs because the `caddy` binary is not installed on your local machine.
If you're running Caddy inside a Docker container, you can format `Caddyfiles` using a containerized command like this:

Docker Compose example:
```yml
caddy:
  image: caddy:latest
  restart: unless-stopped
  cap_add:
    - NET_ADMIN
  ports:
    - "80:80"
    - "443:443"
    - "443:443/udp"
  volumes:
    - ...
  networks:
    - ...
```

Zed `settings.json` configuration:
```json
"languages": {
  "Caddyfile": {
    "format_on_save": "on",
    "tab_size": 2,
    "formatter": {
      "external": {
        "command": "docker",
        "arguments": [
          "compose",
          "exec",
          "-T",           // disable TTY to allow input via stdin
          "caddy",
          "caddy",
          "fmt",
          "-"
        ]
      }
    }
  }
}
```

The `-T` flag disables pseudo-TTY allocation, which is necessary for stdin to work correctly in this context.
The final `"-"` tells `caddy fmt` to read from standard input instead of expecting a file path.
